export default  {
    '01d': '../src/assets/icons/sun-solid.svg',
    '02d': '../src/assets/icons/cloud-sun-solid.svg',
    '03d': '../src/assets/icons/cloud-solid.svg',
    '04d': '../src/assets/icons/cloud-solid.svg',
    '09d': '../src/assets/icons/cloud-rain-solid.svg',
    '10d': '../src/assets/icons/cloud-sun-rain-solid.svg',
    '11d': '../src/assets/icons/bolt-solid.svg',
    '13d': '../src/assets/icons/snowflake-regular.svg',
    '50d': '../src/src/assets/icons/smog-solid.svg',
    '01n': '../src/assets/icons/moon-regular.svg',
    '02n': '../src/assets/icons/cloud-moon-solid.svg',
    '03n': '../src/assets/icons/cloud-moon-solid.svg',
    '04n': '../src/assets/icons/cloud-solid.svg',
    '09n': '../src/assets/icons/cloud-rain-solid.svg',
    '10n': '../src/assets/icons/bolt-solid.svg',
    '11n': '../src/assets/icons/bolt-solid.svg',
    '13n': '../src/assets/icons/snowflake-regular.svg',
    '50n': '../src/assets/icons/smog-solid.svg'
}
